import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import { Toaster } from "sonner";
import GridBackground from "@/components/grid-background";
import { TenantProvider } from "@/store/tenant-context";
import "./globals.css";

import { Grape_Nuts, Crimson_Text } from "next/font/google";

const grapeNuts = Grape_Nuts({
  subsets: ["latin"],
  variable: "--font-display",
  weight: "400",
});

const crimsonText = Crimson_Text({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400", "600"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${grapeNuts.variable} ${crimsonText.variable} ${geistSans.variable}`}>
      <head>
        <Script
          src="https://cdn.jsdelivr.net/npm/signature_pad@4.2.0/dist/signature_pad.umd.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`antialiased relative`}>
        <GridBackground />
        <div className="relative z-10">
          <TenantProvider>
            {children}
          </TenantProvider>
        </div>
        <Toaster
          position="top-right"
          richColors
          closeButton
          expand
        />
      </body>
    </html>
  );
}
